### ISSUE TITLE
Subj.

### ISSUE THREAD

**Issue by dkorolev** [KnowSheet/CTFO_BE#1]

**Comment by dkorolev** [comment]
Something tells me this one is fixed. @mzhurovich ? :-)

**Comment by mzhurovich** [comment]
@dkorolev I wonder, what did you mean by this issue? ))

**Comment by dkorolev** [comment]
That CTFO backend has to be implemented :-)

On Thursday, June 18, 2015, Maxim Zhurovich notifications@github.com
wrote:

> @dkorolev https://github.com/dkorolev I wonder, what did you mean by
> this issue? ))
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KnowSheet/CTFO_BE/issues/1#issuecomment-113388163.

## 

And, as always, have a nice day!
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783
